name = "Runestones"
author = "Ifiht"
version = "4.2.7"
description = "Client modpack for Ithavollr"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f225ded9f2956a3569f9b89223e3e595fbf1c9aae54bfba8b5dff832558ca4a5"

[versions]
fabric = "0.17.3"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
