name = "Runestones"
author = "Ifiht"
version = "4.1.1"
description = "Client modpack for Ithavollr"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "502d5889ede950a7c6c2aebea5af1647e019fa3d5257af54b6ee717431011831"

[versions]
fabric = "0.17.3"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
